version: "3.9"
services:
    chat-app:
        image: gimmitest/chat-app-img
        build:
            context: .
            dockerfile: Dockerfile
            args:
                DEFAULT_PORT: 3000
        container_name: chat
        environment:
            PORT: 3000
        ports:
            - 3000:3000
