apiVersion: apps/v1
kind: Deployment
metadata:
    name: chat-app-deploy
spec:
    replicas: 1
    selector:
        matchLabels:
            app: node
    template:
        metadata:
            labels:
                app: node
        spec:
            containers:
                - name: chat-app
                  image: gimmitest/chat-app-img
                  resources:
                      limits:
                          memory: "128Mi"
                          cpu: "500m"
                  env:
                      - name: PORT
                        value: "3000"
