apiVersion: v1
kind: Service
metadata:
    name: chat-app-service
spec:
    selector:
        app: node
    ports:
        - port: 3000
          targetPort: 3000
          protocol: TCP
    type: NodePort
